<?php 

require_once(dirname(__FILE__).'/../../../config.php');

function xmldb_block_talentospilos_upgrade($oldversion = 0) {
    global $DB;
    $dbman = $DB->get_manager();

    $result = true;

    /// Add a new column newcol to the mdl_myqtype_options
    if ($result && $oldversion < 2017012501) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
        
        
        // Define table talentospilos_instancia to be created.
        $table = new xmldb_table('talentospilos_instancia');

        // Adding fields to table talentospilos_instancia.
        $table->add_field('id', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, XMLDB_SEQUENCE, null);
        $table->add_field('id_instancia', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
        $table->add_field('id_director', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
        $table->add_field('id_programa', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
        $table->add_field('seg_academico', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, null);
        $table->add_field('seg_asistencias', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, null);
        $table->add_field('seg_socioeducativo', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, null);

        // Adding keys to table talentospilos_instancia.
        $table->add_key('primary', XMLDB_KEY_PRIMARY, array('id'));
        $table->add_key('usuario_inst_fk1', XMLDB_KEY_FOREIGN, array('id_director'), 'user', array('id'));
        $table->add_key('usuario_inst_fk2', XMLDB_KEY_FOREIGN, array('id_programa'), 'talentospilos_programa', array('id'));
        $table->add_key('usuario_inst_fk3', XMLDB_KEY_FOREIGN, array('id_instancia'), 'block_instances', array('id'));
        $table->add_key('unique_pk1', XMLDB_KEY_UNIQUE, array('id_director'));
        $table->add_key('unique_pk2', XMLDB_KEY_UNIQUE, array('id_programa'));
        $table->add_key('unique_p3', XMLDB_KEY_UNIQUE, array('id_instancia'));

        // Conditionally launch create table for talentospilos_instancia.
        if (!$dbman->table_exists($table)) {
            $dbman->create_table($table);
        }

        // Talentospilos savepoint reached.
        upgrade_block_savepoint(true, 2017012501, 'talentospilos');
        
    }

    return $result;
}

?>
